spark.executor.memory=4g
spark.executor.cores=2
##spark.driver.extraJavaOptions=-Dsun.security.krb5.debug=true -Dsun.security.jgss.debug=true
#spark.yarn.keytab=/home/cdsw/go01-demo-aws-manishm.keytab
##spark.submit.extraJavaOptions=-Dsun.security.krb5.debug=true -Dsun.security.jgss.debug=true
spark.kerberos.access.hadoopFileSystems=s3a://go01-demo/
